---
name: Отчет об ошибке
about: Создайте отчет, чтобы помочь нам стать лучше
title: ''
labels: '🐛 Баг 🐛'
assignees: ''
---

## 📋 Описание
  Объясните, в чем заключается ошибка и что, по вашему мнению, должно было произойти на самом деле.
  > Пример: При использовании огнетушителя в невесомости игрока не отталкивает назад, хотя должно.

---

## 🔁 Шаги для воспроизведения
Перечислите действия, которые стабильно вызывают эту проблему.

1. Заспавниться за роль X
2. Выполнить действие Y
3. Увидеть результат Z

---

## 💥 Ожидаемое поведение
  Опишите, что должно было произойти.
  > Пример: Огнетушитель должен толкать меня назад в условиях невесомости.

---

## 🧠 Фактическое поведение
  Опишите, что происходит на самом деле.
  > Пример: Ничего не происходит, я просто вишу на месте.

---

## 📸 Скриншоты / Видео
Прикрепите любые скриншоты, видео или логи, которые помогут наглядно показать проблему.

---

## 🗺️ Дополнительные детали
Любая другая информация, которая может помочь, например:
- Карта / ID раунда (если известно)
- Режим игры

---

## 🧩 Примечания
Любая другая информация, которая поможет разработчикам воспроизвести или понять проблему.
Добавьте здесь любой другой контекст.
